/* Service worker for the travel checklist.

   Generated by travel_checklist/generate_site.py — do not hand-edit.

   The cache name embeds a hash of index.html. Regenerating the site changes
   the hash, which changes these bytes, which is what makes the browser notice
   there is a new worker and install it. Without the stamp the old worker would
   keep serving the old checklist forever. */
var CACHE = "travel-checklist-5b44dd678a";
var ASSETS = ["./", "./index.html", "./manifest.webmanifest"];

self.addEventListener("install", function(e) {
  e.waitUntil(caches.open(CACHE).then(function(c) {
    return c.addAll(ASSETS);
  }).then(function() {
    // Don't sit in "waiting" until every tab closes — take over now.
    return self.skipWaiting();
  }));
});

self.addEventListener("activate", function(e) {
  e.waitUntil(caches.keys().then(function(keys) {
    return Promise.all(keys.filter(function(k) { return k !== CACHE; })
                           .map(function(k) { return caches.delete(k); }));
  }).then(function() { return self.clients.claim(); }));
});

/* Stale-while-revalidate.

   The cached copy is still what gets returned, so the app opens instantly in a
   car park with one bar of signal — that property is the whole point and it is
   unchanged. What is new is that every load with signal also refetches in the
   background and overwrites the cache, so the *next* open is fresh.

   Why not rely on the cache stamp alone: a new stamp only reaches the browser
   if it re-requests sw.js, and iOS only does that on a real navigation. A
   home-screen app resumed from the app switcher never navigates, so it could
   sit on a stale cache indefinitely. This path does not depend on the worker
   being replaced at all.

   POSTs from the serve.py edit panel are skipped — a mutation must never be
   answered out of a cache. Cross-origin GETs are left alone entirely. */
self.addEventListener("fetch", function(e) {
  if (e.request.method !== "GET") return;
  if (new URL(e.request.url).origin !== self.location.origin) return;

  // Start the network immediately, independent of the cache lookup below.
  var fresh = fetch(e.request).then(function(res) {
    if (!res || !res.ok) return res;
    var copy = res.clone();   // a body can only be read once; keep one for the cache
    return caches.open(CACHE).then(function(c) {
      return c.put(e.request, copy);
    }).then(function() { return res; });
  });

  // Keep the worker alive until the cache write lands, even though the response
  // we hand back below may already have come from the cache. Swallow the
  // rejection: offline is the normal case, not an error.
  e.waitUntil(fresh.catch(function() {}));

  e.respondWith(caches.match(e.request).then(function(hit) {
    if (hit) return hit;                       // instant, signal or not
    return fresh.catch(function() {            // cold cache and no network
      return caches.match("./index.html");
    });
  }));
});
