/* Service worker for the travel checklist.

   Generated by travel_checklist/generate_site.py — do not hand-edit.

   The cache name embeds a hash of index.html. Regenerating the site changes
   the hash, which changes these bytes, which is what makes the browser notice
   there is a new worker and install it. Without the stamp the old worker would
   keep serving the old checklist forever. */
var CACHE = "travel-checklist-4e183b541d";
var ASSETS = ["./", "./index.html", "./manifest.webmanifest"];

self.addEventListener("install", function(e) {
  e.waitUntil(caches.open(CACHE).then(function(c) {
    return c.addAll(ASSETS);
  }).then(function() {
    // Don't sit in "waiting" until every tab closes — take over now.
    return self.skipWaiting();
  }));
});

self.addEventListener("activate", function(e) {
  e.waitUntil(caches.keys().then(function(keys) {
    return Promise.all(keys.filter(function(k) { return k !== CACHE; })
                           .map(function(k) { return caches.delete(k); }));
  }).then(function() { return self.clients.claim(); }));
});

/* Cache-first: the checklist is a static page and the whole point is that it
   opens instantly in a car park with one bar of signal. Freshness comes from
   regenerating, not from the network.

   POSTs from the serve.py edit panel are skipped — a mutation must never be
   answered out of a cache. */
self.addEventListener("fetch", function(e) {
  if (e.request.method !== "GET") return;
  e.respondWith(caches.match(e.request).then(function(hit) {
    return hit || fetch(e.request).catch(function() {
      return caches.match("./index.html");
    });
  }));
});
